services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 taskpilot.wsgi:application
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:14.15-alpine3.21
    # restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.0-M03-alpine3.21
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    # restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A taskpilot worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A taskpilot beat --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "celery",
          "-A",
          "taskpilot",
          "beat",
          "--max-interval=5",
          "--loglevel=info",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
